# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in remind.gemspec
gemspec

gem 'irb'
gem 'rake', '~> 13.0'

gem 'dotenv', groups: %i[development test]

gem 'whenever', require: false

gem 'thor'

gem 'sqlite3', '~> 2.6'

gem 'pry', '~> 0.15.2'

gem 'json', '~> 2.10', '>= 2.10.2'

gem 'yaml', '~> 0.4.0'
