# frozen_string_literal: true
# This file is auto-generated by Thor CLI
set :output, "/home/vu/Documents/training-ruby/remind/log/cron_log.log"
set :environment, :development

every 1.hour do
  rake 'remind:notify_due_tasks'
end

every 7.days do
  rake 'log:clear'
end


every 1.month do
  rake 'remind:completed_tasks_last_month'
end


